I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script call
    call MyRoom
  File "game/script.rpy", line 48, in script
    bg "rooms/Puzzle_Room.png"
Exception: Sayer 'bg' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script call
    call MyRoom
  File "game/script.rpy", line 48, in script
    bg "rooms/Puzzle_Room.png"
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bg' is not defined.

Darwin-21.6.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Puzzle Test 1 1.0
Mon Jun 26 13:51:59 2023
